/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.RoomDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.RoomClass;

/**
 *
 * @author qn052
 */
public class FrameCanHo extends javax.swing.JFrame {

    /**
     * Creates new form FrameCanHo
     */
    private ArrayList<RoomClass> list;
    DefaultTableModel model;
    RoomDAO daoRoom = new RoomDAO();
    int editIndex;
    private final ArrayList<RoomClass> listNew=new ArrayList<>();    
    EditRoomFrm edit = new EditRoomFrm(this, rootPaneCheckingEnabled);
    
    public FrameCanHo() {
        initComponents();
        this.setLocationRelativeTo(null);
        list = new RoomDAO().getListRoom();
        model = (DefaultTableModel) myTable.getModel();
        model.setColumnIdentifiers(new Object[]{
            "Room", "Owner Name", "Owner Phone"
        });
        showTable();
    }
    public void showTable(){
        list.forEach(r ->{
            model.addRow(new Object[]{
                r.getRoom(), r.getNameBoss(), r.getPhoneBoss()
            });
        });
    }
    public void showSearch(ArrayList<RoomClass>listt){
        for(int i = 0; i < listt.size(); i++)
        {
            model.addRow(new Object[]{
                listt.get(i).getRoom(), listt.get(i).getNameBoss(), list.get(i).getPhoneBoss()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRoom = new javax.swing.JTextField();
        txtNameBoss = new javax.swing.JTextField();
        txtPhoneBoss = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        myTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Room Management");

        btnBack.setText("Home Page");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Room Management");

        jLabel2.setText("Room:");

        jLabel3.setText("Owner Name:");

        jLabel4.setText("Owner Phone:");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        myTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room", "Owner Name", "Owner Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(myTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(260, 260, 260)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhoneBoss, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameBoss, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel1))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNameBoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPhoneBoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnRefresh)
                            .addComponent(btnDelete)
                            .addComponent(btnSearch)
                            .addComponent(btnEdit))))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         new TrangChu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        RoomClass r = new RoomClass();
        
        r.setRoom(txtRoom.getText());
        r.setNameBoss(txtNameBoss.getText());
        r.setPhoneBoss(txtPhoneBoss.getText());
        
        if(new RoomDAO().addRoom(r)){
            JOptionPane.showMessageDialog(rootPane, "Add room success!");
            list.add(r);
            showResult();
        }else{
            JOptionPane.showMessageDialog(rootPane, "This room already exists!");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        
        txtNameBoss.setText("");
        txtPhoneBoss.setText("");
        txtRoom.setText("");
        model.setRowCount(0);
        showTable();
        listNew.clear();
        JOptionPane.showMessageDialog(rootPane, "Refreshed!");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int removeIndex = myTable.getSelectedRow();
        if(removeIndex == -1){
            JOptionPane.showMessageDialog(rootPane, "Select one row, please!");
        }else if(list.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "No information to delete!");
        }else{
            int confirm = JOptionPane.showConfirmDialog(this, "Do you want to delete this room?");
            if(confirm == 0){
                if(!listNew.isEmpty())
                {
                daoRoom.deleteRoom(listNew.get(removeIndex).getRoom());
                listNew.remove(removeIndex);
                }else{
                    daoRoom.deleteRoom(list.get(removeIndex).getRoom());
                    list.remove(removeIndex);
                }
                list.clear();
                list = new RoomDAO().getListRoom();
                listNew.clear();
            }
            model.setRowCount(0);
            showTable();
            
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String keyWord = JOptionPane.showInputDialog(this, "Key Word:");
        //ArrayList<RoomClass> listSearch = new ArrayList<>();
        if(keyWord.length() > 0 && keyWord != null){
            for(int i = 0; i < list.size(); i++)
            {
                if(list.get(i).getRoom().contains(keyWord) || list.get(i).getNameBoss().contains(keyWord)
                        || list.get(i).getPhoneBoss().contains(keyWord))
                    listNew.add(list.get(i));
            }
            model.setRowCount(0);
            showSearch(listNew);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Please write some words");
            model.setRowCount(0);
            showTable();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        editIndex = myTable.getSelectedRow();
        if(editIndex == -1){
            JOptionPane.showMessageDialog(rootPane, "Select one row, please!");
        }else if(list.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "No information to delete!");
        }else{
            int confirm = JOptionPane.showConfirmDialog(this, "Do you want to edit?");
            if(confirm == 0){  
                if(!listNew.isEmpty())
                {
                    edit.setEditData(listNew.get(editIndex));
                    edit.setVisible(true);
                    
                }else{
                    edit.setEditData(list.get(editIndex));
                    edit.setVisible(true);
                }
                
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed
    
    public void showResult(){
        RoomClass r =list.get(list.size() - 1);
        model.addRow(new Object[]{
            r.getRoom(), r.getNameBoss(), r.getPhoneBoss()
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCanHo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCanHo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCanHo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCanHo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCanHo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable myTable;
    private javax.swing.JTextField txtNameBoss;
    private javax.swing.JTextField txtPhoneBoss;
    private javax.swing.JTextField txtRoom;
    // End of variables declaration//GEN-END:variables

    void updateRoom(RoomClass r) {
        r = new RoomClass();
        System.out.println(editIndex);
        
        String roomEdit = edit.getTxtRoom().getText();
        String nameBossEdit = edit.getTxtNameBoss().getText();
        String phoneBossEdit = edit.getTxtPhoneBoss().getText();
        
        r.setRoom(roomEdit);
        r.setNameBoss(nameBossEdit);
        r.setPhoneBoss(phoneBossEdit);
        
        if(!listNew.isEmpty())
        {
            daoRoom.editRoom(listNew.get(editIndex).getRoom(), r);
        }else{
            daoRoom.editRoom(list.get(editIndex).getRoom(), r);
        }        
        list.clear();
        list = new RoomDAO().getListRoom();
        model.setRowCount(0);
        showTable();
    }
}
