/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.VehicleDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.VehicleClass;

/**
 *
 * @author qn052
 */
public class FramePhuongTien extends javax.swing.JFrame {

    /**
     * Creates new form FramePhuongTien
     */
    private ArrayList<VehicleClass> list;
    DefaultTableModel model;
    VehicleDAO daoVehicle = new VehicleDAO();
    int editIndex;
    private final ArrayList<VehicleClass> listNew=new ArrayList<>();
    EditVehicleFrm edit = new EditVehicleFrm(this, rootPaneCheckingEnabled);
    
    public FramePhuongTien() {
        initComponents();
        this.setLocationRelativeTo(null);
        list = new VehicleDAO().getListVehicle();
        model = (DefaultTableModel) myTable.getModel();
        model.setColumnIdentifiers(new Object[]{
            "Number Plate", "Type", "Owner Phone", "Owner Name"
        });
        showTable();
    }
    public void showTable(){
        list.forEach(v ->{
            model.addRow(new Object[]{
                v.getNumberPlate(), v.getType(), v.getPhoneBoss(), v.getNameBoss()
            });
        });
    }
    public void showSearch(ArrayList<VehicleClass>listt){
        for(int i = 0; i < listt.size(); i++)
        {
            model.addRow(new Object[]{
                listt.get(i).getNumberPlate(), listt.get(i).getType(), listt.get(i).getPhoneBoss(), listt.get(i).getNameBoss()
            });
        }
    }
    public void showResult(){
        VehicleClass v =list.get(list.size() - 1);
        model.addRow(new Object[]{
            v.getNumberPlate(), v.getType(), v.getPhoneBoss(), v.getNameBoss()
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNumberPlate = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        txtPhoneBoss = new javax.swing.JTextField();
        txtNameBoss = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        myTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vehicle Management");

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseline_home_black_18dp.png"))); // NOI18N
        btnBack.setText("Home Page");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Phuongtien.png"))); // NOI18N
        jLabel1.setText("Vehicle Management");

        jLabel2.setText("Number Plate:");

        jLabel3.setText("Type:");

        jLabel4.setText("Owner Phone:");

        jLabel5.setText("Owner Name:");

        txtNameBoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameBossActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restart.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xoa.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tim.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit2.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        myTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number Plate", "Type", "Owner Phone", "Owner Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(myTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPhoneBoss, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(txtNameBoss)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNumberPlate, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(txtType))))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(247, 247, 247)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNumberPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPhoneBoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtNameBoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnRefresh)
                            .addComponent(btnDelete)
                            .addComponent(btnSearch)
                            .addComponent(btnEdit)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new TrangChu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtNameBossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameBossActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameBossActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        VehicleClass v = new VehicleClass();
        
        v.setNumberPlate(txtNumberPlate.getText());
        v.setType(txtType.getText());
        v.setPhoneBoss(txtPhoneBoss.getText());
        v.setNameBoss(txtNameBoss.getText());
        
        if(new VehicleDAO().addVehicle(v)){
            JOptionPane.showMessageDialog(rootPane, "Add vehicle success!");
            list.add(v);
            showResult();
            model.setRowCount(0);
            showTable();
        }else{
            JOptionPane.showMessageDialog(rootPane, "This vehicle already exists!");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
       
        txtNameBoss.setText("");
        txtNumberPlate.setText("");
        txtPhoneBoss.setText("");
        txtType.setText("");
        
        model.setRowCount(0);
        showTable();
        listNew.clear();
        
        JOptionPane.showMessageDialog(rootPane, "Refreshed!");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int removeIndex = myTable.getSelectedRow();
        if(removeIndex == -1){
            JOptionPane.showMessageDialog(rootPane, "Select one row, please!");
        }else if(list.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "No information to delete!");
        }else{
            int confirm = JOptionPane.showConfirmDialog(this, "Do you want to delete this room?");
            if(confirm == 0){
                if(!listNew.isEmpty())
                {
                    daoVehicle.deleteVehicle(listNew.get(removeIndex).getNumberPlate());
                    listNew.remove(removeIndex);
                }else{
                    daoVehicle.deleteVehicle(list.get(removeIndex).getNumberPlate());
                    list.remove(removeIndex);
                }
                list.clear();
                list = new VehicleDAO().getListVehicle();
                listNew.clear();
            }
            model.setRowCount(0);
            showTable();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
               String keyWord = JOptionPane.showInputDialog(this, "Key Word:");
        //ArrayList<VehicleClass> listSearch = new ArrayList<>();
        if(keyWord.length() > 0 && keyWord != null){
            for(int i = 0; i < list.size(); i++)
            {
                if(list.get(i).getNumberPlate().contains(keyWord) || list.get(i).getType().contains(keyWord)
                        || list.get(i).getPhoneBoss().contains(keyWord) || list.get(i).getNameBoss().contains(keyWord))
                    listNew.add(list.get(i));
            }
            model.setRowCount(0);
            showSearch(listNew);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Please write some words");
            model.setRowCount(0);
            showTable();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        editIndex = myTable.getSelectedRow();
        if(editIndex == -1){
            JOptionPane.showMessageDialog(rootPane, "Select one row, please!");
        }else if(list.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "No information to delete!");
        }else{
            int confirm = JOptionPane.showConfirmDialog(this, "Do you want to edit?");
            if(confirm == 0){     
                if(!listNew.isEmpty())
                {
                    edit.setEditData(listNew.get(editIndex));
                    edit.setVisible(true);
                }else{
                    edit.setEditData(list.get(editIndex));
                    edit.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePhuongTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePhuongTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePhuongTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePhuongTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePhuongTien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable myTable;
    private javax.swing.JTextField txtNameBoss;
    private javax.swing.JTextField txtNumberPlate;
    private javax.swing.JTextField txtPhoneBoss;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables

    void updateVehicle(VehicleClass v) {
        v = new VehicleClass();
        String numberPlateEdit = edit.getTxtNumberPlate().getText();
        String typeEdit = edit.getTxtType().getText();
        String phoneBossEdit = edit.getTxtPhoneBoss().getText();
        String nameBossEdit = edit.getTxtNameBoss().getText();
        
        v.setNumberPlate(numberPlateEdit);
        v.setType(typeEdit);
        v.setPhoneBoss(phoneBossEdit);
        v.setNameBoss(nameBossEdit);
        
        if(!listNew.isEmpty())
        {
            daoVehicle.editVehicle(listNew.get(editIndex).getNumberPlate(), v);
        }else{
            daoVehicle.editVehicle(list.get(editIndex).getNumberPlate(), v);
        }
        list.clear();
        list = new VehicleDAO().getListVehicle();
        model.setRowCount(0);
        showTable();
    }
}
