/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author qn052
 */
public class TrangChu extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnRoom.addActionListener(this);
        btnPeople.addActionListener(this);
        btnVehicle.addActionListener(this);
        btnService.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTrangChu = new javax.swing.JLabel();
        btnRoom = new javax.swing.JButton();
        btnPeople = new javax.swing.JButton();
        btnVehicle = new javax.swing.JButton();
        btnService = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Apartment Manager");

        labelTrangChu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTrangChu.setForeground(new java.awt.Color(51, 51, 255));
        labelTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTrangChu.setIcon(new javax.swing.ImageIcon("C:\\Users\\qn052\\OneDrive\\Desktop\\Untitled.png")); // NOI18N
        labelTrangChu.setText("Home Page");
        labelTrangChu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelTrangChu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Canho.png"))); // NOI18N
        btnRoom.setText("Room Management");
        btnRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomActionPerformed(evt);
            }
        });

        btnPeople.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nguoi.png"))); // NOI18N
        btnPeople.setText("People Management");
        btnPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeopleActionPerformed(evt);
            }
        });

        btnVehicle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Phuongtien.png"))); // NOI18N
        btnVehicle.setText("Vehicle Management");

        btnService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dichvu.png"))); // NOI18N
        btnService.setText("Cost Management");
        btnService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTrangChu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPeople, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(btnRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(btnVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(btnService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTrangChu)
                .addGap(27, 27, 27)
                .addComponent(btnRoom)
                .addGap(38, 38, 38)
                .addComponent(btnPeople)
                .addGap(38, 38, 38)
                .addComponent(btnVehicle)
                .addGap(34, 34, 34)
                .addComponent(btnService)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRoomActionPerformed

    private void btnPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeopleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeopleActionPerformed

    private void btnServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnServiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TrangChu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPeople;
    private javax.swing.JButton btnRoom;
    private javax.swing.JButton btnService;
    private javax.swing.JButton btnVehicle;
    private javax.swing.JLabel labelTrangChu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(btnPeople)){
            btnPeopleClick();
        }
        else if(e.getSource().equals(btnRoom)){
            btnRoomClick();
        }
        else if(e.getSource().equals(btnVehicle)){
            btnVehicleClick();
        }
        else{
            btnServiceClick();
        }
            
    }
    
    public void btnPeopleClick(){
        new FrameDanCu().setVisible(true);
        this.dispose();
    }
    
    public void btnRoomClick(){
        new FrameCanHo().setVisible(true);
        this.dispose();
    }
    
    public void btnVehicleClick(){
        new FramePhuongTien().setVisible(true);
        this.dispose();
    }
    
    public void btnServiceClick(){
        new FrameChiPhi().setVisible(true);
        this.dispose();
    }
    
    
    
}
